### PR TITLE
Add nix package install methods

### PR DESCRIPTION
**Pull request by HeitorAugustoLN**
I created a nix package for this widget. It is going to be available in nixos-unstable and nixpkgs-unstable in a few days.

### CODE REVIEW

**Comment by luisbocanegra** [comment]
Hi, this is awesome.

> It is going to be available in nixos-unstable and nixpkgs-unstable in a few days.

So I should wait before merging, right? If so, will you ping me when they become available or where can I check when that happens? (I've never used nix/NixOS)

Thank you!

**Comment by HeitorAugustoLN** [comment]
> So I should wait before merging, right?

Yes.

It is already merged, but before it gets into nixos-unstable (rolling variant of NixOS) the packages are tested. (Generally takes 3 days after being merged)

You can check it in https://nixpk.gs/pr-tracker.html?pr=331149, if it loads for you (it doesn't work for me for some days now).

But i am checking it every day, so when it becomes available I ping you.

**Comment by HeitorAugustoLN** [comment]
I've also created a package for plasma-panel-spacer-extended too. So when it gets merged I will probably create another pull request for it in plasma-panel-spacer-extended repository

**Comment by luisbocanegra** [comment]
> But i am checking it every day, so when it becomes available I ping you.

Thanks.

> I've also created a package for plasma-panel-spacer-extended too. So when it gets merged I will probably create another pull request for it in plasma-panel-spacer-extended repository

Thanks a lot for your contributions, highly appreciated.

**Comment by HeitorAugustoLN** [comment]
> > But i am checking it every day, so when it becomes available I ping you.
> 
> Thanks.
> 
> > I've also created a package for plasma-panel-spacer-extended too. So when it gets merged I will probably create another pull request for it in plasma-panel-spacer-extended repository
> 
> Thanks a lot for your contributions, highly appreciated.

Thanks a lot! Your work on the plasma widgets are awesome.

**Comment by HeitorAugustoLN** [comment]
@luisbocanegra the package is now available https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/pl/plasma-panel-colorizer/package.nix

**Comment by luisbocanegra** [comment]
Thanks. Merging

**Pull request merged**
